Import

In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Import dataset


In [40]:
dataset = pd.read_csv('data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [41]:
print(x)

[['Argentina' 34.0 nan]
 ['Argentina' 31.0 1500.0]
 ['Argentina' 39.0 900.0]
 ['USA' 38.0 1100.0]
 ['USA' 30.0 1300.0]
 ['USA' nan 1000.0]
 ['Uzbekistan' 36.0 1400.0]
 ['Uzbekistan' 33.0 800.0]
 ['Uzbekistan' 35.0 1000.0]
 ['Argentina' 40.0 1250.0]
 ['Argentina' 35.0 950.0]
 ['Argentina' 37.0 1050.0]
 ['USA' 30.0 1150.0]
 ['USA' 32.0 nan]
 ['USA' 34.0 1450.0]]


In [42]:
print(y)

['Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'No' 'Yes']


care missing data


In [43]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [44]:
print(x)

[['Argentina' 34.0 1142.3076923076924]
 ['Argentina' 31.0 1500.0]
 ['Argentina' 39.0 900.0]
 ['USA' 38.0 1100.0]
 ['USA' 30.0 1300.0]
 ['USA' 34.57142857142857 1000.0]
 ['Uzbekistan' 36.0 1400.0]
 ['Uzbekistan' 33.0 800.0]
 ['Uzbekistan' 35.0 1000.0]
 ['Argentina' 40.0 1250.0]
 ['Argentina' 35.0 950.0]
 ['Argentina' 37.0 1050.0]
 ['USA' 30.0 1150.0]
 ['USA' 32.0 1142.3076923076924]
 ['USA' 34.0 1450.0]]


encode


In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder="passthrough")
X = np.array(ct.fit_transform(x))


In [46]:
print(X)

[[1.0 0.0 0.0 34.0 1142.3076923076924]
 [1.0 0.0 0.0 31.0 1500.0]
 [1.0 0.0 0.0 39.0 900.0]
 [0.0 1.0 0.0 38.0 1100.0]
 [0.0 1.0 0.0 30.0 1300.0]
 [0.0 1.0 0.0 34.57142857142857 1000.0]
 [0.0 0.0 1.0 36.0 1400.0]
 [0.0 0.0 1.0 33.0 800.0]
 [0.0 0.0 1.0 35.0 1000.0]
 [1.0 0.0 0.0 40.0 1250.0]
 [1.0 0.0 0.0 35.0 950.0]
 [1.0 0.0 0.0 37.0 1050.0]
 [0.0 1.0 0.0 30.0 1150.0]
 [0.0 1.0 0.0 32.0 1142.3076923076924]
 [0.0 1.0 0.0 34.0 1450.0]]


In [47]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [48]:
print(y)

[1 1 1 0 1 0 1 1 0 1 1 0 1 0 1]


splitting the dataset into the training set and test set

In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [52]:
print(X_train)

[[1.0 0.0 0.0 39.0 900.0]
 [1.0 0.0 0.0 35.0 950.0]
 [0.0 1.0 0.0 30.0 1300.0]
 [1.0 0.0 0.0 31.0 1500.0]
 [0.0 1.0 0.0 32.0 1142.3076923076924]
 [1.0 0.0 0.0 34.0 1142.3076923076924]
 [0.0 1.0 0.0 34.0 1450.0]
 [1.0 0.0 0.0 40.0 1250.0]
 [0.0 0.0 1.0 35.0 1000.0]
 [0.0 1.0 0.0 30.0 1150.0]
 [1.0 0.0 0.0 37.0 1050.0]
 [0.0 1.0 0.0 34.57142857142857 1000.0]]


In [53]:
print(X_test)

[[0.0 1.0 0.0 38.0 1100.0]
 [0.0 0.0 1.0 33.0 800.0]
 [0.0 0.0 1.0 36.0 1400.0]]


In [54]:
print(y_train)

[1 1 1 1 0 1 1 1 0 1 0 0]


In [55]:
print(y_test)

[0 1 1]


FEATURE SCALING

In [56]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.fit_transform(X_test[:, 3:])

In [57]:
print(X_train)

[[1.0 0.0 0.0 1.5107289068318148 -1.3807660946485933]
 [1.0 0.0 0.0 0.22565317848880373 -1.1077629124367043]
 [0.0 1.0 0.0 -1.38069148193996 0.8032593630465193]
 [1.0 0.0 0.0 -1.0594225498542074 1.8952720918940757]
 [0.0 1.0 0.0 -0.7381536177684546 -0.057750673160207405]
 [1.0 0.0 0.0 -0.09561575359694903 -0.057750673160207405]
 [0.0 1.0 0.0 -0.09561575359694903 1.6222689096821865]
 [1.0 0.0 0.0 1.8319978389175675 0.5302561808346302]
 [0.0 0.0 1.0 0.22565317848880373 -0.8347597302248152]
 [0.0 1.0 0.0 -1.38069148193996 -0.015750183589147926]
 [1.0 0.0 0.0 0.8681910426603092 -0.5617565480129261]
 [0.0 1.0 0.0 0.08796649330919476 -0.8347597302248152]]


In [58]:
print(X_test)

[[0.0 1.0 0.0 1.1355499479153388 0.0]
 [0.0 0.0 1.0 -1.297771369046099 -1.224744871391589]
 [0.0 0.0 1.0 0.16222142113076368 1.224744871391589]]
